#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# ssh-agent if it's not alreaddy running
[ -n "$SSH_AUTH_SOCK" ] || eval $(ssh-agent)


# select wm/de with: startx ~/.xinitrc session
session=${1:-awesome}

case "$session" in
    awesome)
        exec awesome ;;
    alacritty)
        exec alacritty --dimensions 213 56 ;;
    *)
        exec "$session"
esac
